### ISSUE TITLE
license is not clear 

### ISSUE THREAD

**Issue by seekingdeep** [FactoDeepLearning/LinePytorchOCR#3]
Hi there,
the included license `Cecill-C` is not clear to me.
can it be used for commercial usage, redistributed? etc....

wouldn't it be better to use a simpler license such as apache or bsc, etc...

**Comment by FactoDeepLearning** [comment]
Hi,

It is not that easy, commonly used licenses are not fully recognized by French government concerning author rights.

So yes, it can be used for commercial usage and redistributed. But in case of public redistribution, direct contribution to the original source should be distributed under the same license, rest of the project can be distributed under other license.

More information here: https://cecill.info/index.en.html

**Comment by seekingdeep** [comment]
`direct contribution to the original source should be distributed under the same license`
do you mean that i should include the license file `LICENSE.md` when redistributed?

**Comment by FactoDeepLearning** [comment]
"CeCILL-C is well suited to libraries and more generally software components. Anyone distributing an application which includes components under the CeCILL-C license must mention this fact and make any changes to the source code of these components available to the community under CECILL-C while being free to choose the licence of its application."

So the answer is yes. To go further, best practice implies to also include header in each source file.

**Comment by seekingdeep** [comment]
thanks
